"""Reference/lookup data seeded into the schema (idempotent).

Categories, countries, and languages use fixed codes so downstream code and
queries can rely on stable identifiers. The ranking configs mirror spec §13.
"""

from backend.db.models import Category, Country, Language, RankingConfig

CATEGORIES: list[dict] = [
    {"code": "politics", "label": "Politics"},
    {"code": "business", "label": "Business"},
    {"code": "technology", "label": "Technology"},
    {"code": "science", "label": "Science"},
    {"code": "health", "label": "Health"},
    {"code": "sports", "label": "Sports"},
    {"code": "entertainment", "label": "Entertainment"},
    {"code": "world", "label": "World"},
    {"code": "other", "label": "Other"},
]

COUNTRIES: list[dict] = [
    {"code": "AF", "name": "Afghanistan"},
    {"code": "AL", "name": "Albania"},
    {"code": "DZ", "name": "Algeria"},
    {"code": "AR", "name": "Argentina"},
    {"code": "AU", "name": "Australia"},
    {"code": "AT", "name": "Austria"},
    {"code": "BD", "name": "Bangladesh"},
    {"code": "BE", "name": "Belgium"},
    {"code": "BR", "name": "Brazil"},
    {"code": "BG", "name": "Bulgaria"},
    {"code": "CA", "name": "Canada"},
    {"code": "CL", "name": "Chile"},
    {"code": "CN", "name": "China"},
    {"code": "CO", "name": "Colombia"},
    {"code": "HR", "name": "Croatia"},
    {"code": "CU", "name": "Cuba"},
    {"code": "CZ", "name": "Czechia"},
    {"code": "DK", "name": "Denmark"},
    {"code": "EG", "name": "Egypt"},
    {"code": "ET", "name": "Ethiopia"},
    {"code": "FI", "name": "Finland"},
    {"code": "FR", "name": "France"},
    {"code": "DE", "name": "Germany"},
    {"code": "GH", "name": "Ghana"},
    {"code": "GR", "name": "Greece"},
    {"code": "HK", "name": "Hong Kong"},
    {"code": "HU", "name": "Hungary"},
    {"code": "IN", "name": "India"},
    {"code": "ID", "name": "Indonesia"},
    {"code": "IR", "name": "Iran"},
    {"code": "IQ", "name": "Iraq"},
    {"code": "IE", "name": "Ireland"},
    {"code": "IL", "name": "Israel"},
    {"code": "IT", "name": "Italy"},
    {"code": "JP", "name": "Japan"},
    {"code": "JO", "name": "Jordan"},
    {"code": "KE", "name": "Kenya"},
    {"code": "KP", "name": "North Korea"},
    {"code": "KR", "name": "South Korea"},
    {"code": "KW", "name": "Kuwait"},
    {"code": "LB", "name": "Lebanon"},
    {"code": "MY", "name": "Malaysia"},
    {"code": "MX", "name": "Mexico"},
    {"code": "MA", "name": "Morocco"},
    {"code": "MM", "name": "Myanmar"},
    {"code": "NL", "name": "Netherlands"},
    {"code": "NZ", "name": "New Zealand"},
    {"code": "NG", "name": "Nigeria"},
    {"code": "NO", "name": "Norway"},
    {"code": "PK", "name": "Pakistan"},
    {"code": "PS", "name": "Palestine"},
    {"code": "PE", "name": "Peru"},
    {"code": "PH", "name": "Philippines"},
    {"code": "PL", "name": "Poland"},
    {"code": "PT", "name": "Portugal"},
    {"code": "QA", "name": "Qatar"},
    {"code": "RO", "name": "Romania"},
    {"code": "RU", "name": "Russia"},
    {"code": "SA", "name": "Saudi Arabia"},
    {"code": "RS", "name": "Serbia"},
    {"code": "SG", "name": "Singapore"},
    {"code": "ZA", "name": "South Africa"},
    {"code": "ES", "name": "Spain"},
    {"code": "SE", "name": "Sweden"},
    {"code": "CH", "name": "Switzerland"},
    {"code": "SY", "name": "Syria"},
    {"code": "TW", "name": "Taiwan"},
    {"code": "TH", "name": "Thailand"},
    {"code": "TR", "name": "Turkey"},
    {"code": "UA", "name": "Ukraine"},
    {"code": "AE", "name": "United Arab Emirates"},
    {"code": "GB", "name": "United Kingdom"},
    {"code": "US", "name": "United States"},
    {"code": "UY", "name": "Uruguay"},
    {"code": "VE", "name": "Venezuela"},
    {"code": "VN", "name": "Vietnam"},
    {"code": "YE", "name": "Yemen"},
    {"code": "ZW", "name": "Zimbabwe"},
]

LANGUAGES: list[dict] = [
    {"code": "en", "name": "English"},
    {"code": "es", "name": "Spanish"},
    {"code": "fr", "name": "French"},
    {"code": "de", "name": "German"},
    {"code": "it", "name": "Italian"},
    {"code": "pt", "name": "Portuguese"},
    {"code": "ru", "name": "Russian"},
    {"code": "zh", "name": "Chinese"},
    {"code": "ja", "name": "Japanese"},
    {"code": "ko", "name": "Korean"},
    {"code": "ar", "name": "Arabic"},
    {"code": "hi", "name": "Hindi"},
    {"code": "bn", "name": "Bengali"},
    {"code": "ur", "name": "Urdu"},
    {"code": "tr", "name": "Turkish"},
    {"code": "nl", "name": "Dutch"},
    {"code": "pl", "name": "Polish"},
    {"code": "sv", "name": "Swedish"},
    {"code": "no", "name": "Norwegian"},
    {"code": "da", "name": "Danish"},
    {"code": "fi", "name": "Finnish"},
    {"code": "el", "name": "Greek"},
    {"code": "he", "name": "Hebrew"},
    {"code": "fa", "name": "Persian"},
    {"code": "id", "name": "Indonesian"},
    {"code": "ms", "name": "Malay"},
    {"code": "th", "name": "Thai"},
    {"code": "vi", "name": "Vietnamese"},
    {"code": "uk", "name": "Ukrainian"},
    {"code": "cs", "name": "Czech"},
    {"code": "ro", "name": "Romanian"},
    {"code": "hu", "name": "Hungarian"},
    {"code": "sw", "name": "Swahili"},
    {"code": "ta", "name": "Tamil"},
    {"code": "te", "name": "Telugu"},
    {"code": "pa", "name": "Punjabi"},
]

# spec §13 — intent-dependent weights (intent, w_sim, w_fresh, w_cred, w_event)
RANKING_CONFIGS: list[dict] = [
    {"intent": "recency", "w_sim": 0.35, "w_fresh": 0.40, "w_cred": 0.15, "w_event": 0.10},
    {"intent": "default", "w_sim": 0.55, "w_fresh": 0.20, "w_cred": 0.15, "w_event": 0.10},
    {"intent": "historical", "w_sim": 0.70, "w_fresh": 0.05, "w_cred": 0.15, "w_event": 0.10},
]

SEED_MODELS: dict = {
    Category: CATEGORIES,
    Country: COUNTRIES,
    Language: LANGUAGES,
    RankingConfig: RANKING_CONFIGS,
}
