"""add author column to articles (FR-5)

Revision ID: 6928a7f1c674
Revises: e4a30858967d
Create Date: 2026-08-11 00:50:04.897717

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6928a7f1c674"
down_revision: str | Sequence[str] | None = "e4a30858967d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("articles", sa.Column("author", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("articles", "author")
    # ### end Alembic commands ###
