"""spec v2.0 full schema (Phase 1)

Revision ID: e4a30858967d
Revises: f6d6fc5f26ef
Create Date: 2026-08-11 00:35:01.206664

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from backend.db.seed_data import CATEGORIES, COUNTRIES, LANGUAGES, RANKING_CONFIGS
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e4a30858967d"
down_revision: str | Sequence[str] | None = "f6d6fc5f26ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the legacy pre-spec skeleton tables if present (they were created by
    # revision f6d6fc5f26ef with a different shape; the data is throwaway dev data).
    op.execute("DROP TABLE IF EXISTS articles CASCADE")
    op.execute("DROP TABLE IF EXISTS sources CASCADE")
    op.execute("DROP TABLE IF EXISTS events CASCADE")
    op.create_table(
        "categories",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_categories")),
    )
    op.create_table(
        "countries",
        sa.Column("code", sa.CHAR(length=2), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_countries")),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), server_default=sa.text("0.5"), nullable=False),
        sa.Column("status", sa.String(length=16), server_default=sa.text("'open'"), nullable=False),
        sa.Column("centroid_vector_id", sa.UUID(), nullable=True),
        sa.Column("article_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('open', 'closed')", name=op.f("ck_events_status_valid")),
        sa.CheckConstraint("confidence BETWEEN 0 AND 1", name=op.f("ck_events_confidence_range")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_index(
        "ix_events_confidence", "events", [sa.literal_column("confidence DESC")], unique=False
    )
    op.create_index(
        "ix_events_status_updated",
        "events",
        ["status", sa.literal_column("last_updated DESC")],
        unique=False,
    )
    op.create_table(
        "languages",
        sa.Column("code", sa.CHAR(length=2), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_languages")),
    )
    op.create_table(
        "ranking_configs",
        sa.Column("intent", sa.String(length=32), nullable=False),
        sa.Column("w_sim", sa.Float(), nullable=False),
        sa.Column("w_fresh", sa.Float(), nullable=False),
        sa.Column("w_cred", sa.Float(), nullable=False),
        sa.Column("w_event", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("intent", name=op.f("pk_ranking_configs")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("display_name", sa.String(length=128), nullable=True),
        sa.Column("role", sa.String(length=16), server_default=sa.text("'user'"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('user', 'analyst', 'admin')", name=op.f("ck_users_role_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("key_hash", sa.Text(), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=True),
        sa.Column(
            "scopes",
            postgresql.ARRAY(sa.String()),
            server_default=sa.text("ARRAY['read']::text[]"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_api_keys_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("key_hash", name=op.f("uq_api_keys_key_hash")),
    )
    op.create_index("ix_api_keys_user", "api_keys", ["user_id"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=True),
        sa.Column("target_id", sa.UUID(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_audit_log_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(
        "ix_audit_log_action_time",
        "audit_log",
        ["action", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_audit_log_user_time",
        "audit_log",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "notification_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("keyword_or_topic", sa.Text(), nullable=True),
        sa.Column("category_code", sa.String(length=32), nullable=True),
        sa.Column(
            "channel", sa.String(length=16), server_default=sa.text("'email'"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "channel IN ('email', 'in_app')", name=op.f("ck_notification_rules_channel_valid")
        ),
        sa.ForeignKeyConstraint(
            ["category_code"],
            ["categories.code"],
            name=op.f("fk_notification_rules_category_code_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notification_rules_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_rules")),
    )
    op.create_index("ix_notification_rules_user", "notification_rules", ["user_id"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index("ix_refresh_tokens_user", "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "saved_reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column(
            "content",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("query", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_saved_reports_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_reports")),
    )
    op.create_index(
        "ix_saved_reports_user",
        "saved_reports",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "saved_searches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column(
            "filters",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_saved_searches_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_searches")),
    )
    op.create_index("ix_saved_searches_user", "saved_searches", ["user_id"], unique=False)
    op.create_table(
        "sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("rss_url", sa.Text(), nullable=True),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column("credibility_score", sa.Float(), server_default=sa.text("0.5"), nullable=False),
        sa.Column(
            "credibility_method",
            sa.String(length=32),
            server_default=sa.text("'manual'"),
            nullable=False,
        ),
        sa.Column("category_code", sa.String(length=32), nullable=True),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column(
            "poll_interval_minutes", sa.Integer(), server_default=sa.text("15"), nullable=False
        ),
        sa.Column("last_polled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "consecutive_failures", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "credibility_method IN ('manual', 'external_dataset', 'computed')",
            name=op.f("ck_sources_credibility_method_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'degraded', 'disabled')", name=op.f("ck_sources_status_valid")
        ),
        sa.CheckConstraint(
            "credibility_score BETWEEN 0 AND 1", name=op.f("ck_sources_credibility_score_range")
        ),
        sa.CheckConstraint(
            "poll_interval_minutes >= 5", name=op.f("ck_sources_poll_interval_min_5")
        ),
        sa.ForeignKeyConstraint(
            ["category_code"], ["categories.code"], name=op.f("fk_sources_category_code_categories")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
    )
    op.create_index("ix_sources_status", "sources", ["status"], unique=False)
    op.create_table(
        "articles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("content_ref", sa.Text(), nullable=True),
        sa.Column("content_preview", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("url_hash", sa.String(length=64), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("language_code", sa.CHAR(length=2), nullable=True),
        sa.Column("category_code", sa.String(length=32), nullable=True),
        sa.Column("country_code", sa.CHAR(length=2), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_code"],
            ["categories.code"],
            name=op.f("fk_articles_category_code_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["country_code"], ["countries.code"], name=op.f("fk_articles_country_code_countries")
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_articles_event_id_events")
        ),
        sa.ForeignKeyConstraint(
            ["language_code"], ["languages.code"], name=op.f("fk_articles_language_code_languages")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_articles_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_articles")),
        sa.UniqueConstraint("url_hash", name="uq_articles_url_hash"),
    )
    op.create_index("ix_articles_category", "articles", ["category_code"], unique=False)
    op.create_index("ix_articles_event_id", "articles", ["event_id"], unique=False)
    op.create_index("ix_articles_language", "articles", ["language_code"], unique=False)
    op.create_index(
        "ix_articles_published_at",
        "articles",
        [sa.literal_column("published_at DESC")],
        unique=False,
    )
    op.create_index("ix_articles_source_id", "articles", ["source_id"], unique=False)
    op.create_table(
        "article_chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column("chunk_number", sa.Integer(), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("qdrant_point_id", sa.UUID(), nullable=True),
        sa.Column(
            "embedding_status",
            sa.String(length=16),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "embedding_status IN ('pending', 'embedded', 'failed')",
            name=op.f("ck_article_chunks_embedding_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_article_chunks_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_article_chunks")),
        sa.UniqueConstraint("article_id", "chunk_number", name="uq_article_chunks_number"),
    )
    op.create_index("ix_chunks_article_id", "article_chunks", ["article_id"], unique=False)
    op.create_index(
        "ix_chunks_embedding_status", "article_chunks", ["embedding_status"], unique=False
    )
    op.create_table(
        "bookmarks",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_bookmarks_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_bookmarks_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "article_id", name=op.f("pk_bookmarks")),
    )
    op.create_table(
        "event_articles",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column("similarity_at_match", sa.Float(), nullable=True),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_event_articles_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_event_articles_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("event_id", "article_id", name=op.f("pk_event_articles")),
    )
    op.create_index("ix_event_articles_article", "event_articles", ["article_id"], unique=False)
    op.create_index("ix_event_articles_event", "event_articles", ["event_id"], unique=False)
    # ### end Alembic commands ###

    # --- Reference/lookup data (spec §10, FR-7 taxonomy) ---------------------
    _seed_reference_data()


def _seed_reference_data() -> None:
    """Insert the fixed lookup rows (categories, countries, languages, weights).

    Data lives in ``backend.db.seed_data`` so the app and the migration share
    one source of truth; the startup seeder keeps it idempotent.
    """
    categories = sa.table(
        "categories",
        sa.column("code", sa.String(32)),
        sa.column("label", sa.String(64)),
    )
    op.bulk_insert(categories, CATEGORIES)

    countries = sa.table(
        "countries",
        sa.column("code", sa.CHAR(2)),
        sa.column("name", sa.String(64)),
    )
    op.bulk_insert(countries, COUNTRIES)

    languages = sa.table(
        "languages",
        sa.column("code", sa.CHAR(2)),
        sa.column("name", sa.String(64)),
    )
    op.bulk_insert(languages, LANGUAGES)

    ranking_configs = sa.table(
        "ranking_configs",
        sa.column("intent", sa.String(32)),
        sa.column("w_sim", sa.Float()),
        sa.column("w_fresh", sa.Float()),
        sa.column("w_cred", sa.Float()),
        sa.column("w_event", sa.Float()),
    )
    op.bulk_insert(ranking_configs, RANKING_CONFIGS)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_event_articles_event", table_name="event_articles")
    op.drop_index("ix_event_articles_article", table_name="event_articles")
    op.drop_table("event_articles")
    op.drop_table("bookmarks")
    op.drop_index("ix_chunks_embedding_status", table_name="article_chunks")
    op.drop_index("ix_chunks_article_id", table_name="article_chunks")
    op.drop_table("article_chunks")
    op.drop_index("ix_articles_source_id", table_name="articles")
    op.drop_index("ix_articles_published_at", table_name="articles")
    op.drop_index("ix_articles_language", table_name="articles")
    op.drop_index("ix_articles_event_id", table_name="articles")
    op.drop_index("ix_articles_category", table_name="articles")
    op.drop_table("articles")
    op.drop_index("ix_sources_status", table_name="sources")
    op.drop_table("sources")
    op.drop_index("ix_saved_searches_user", table_name="saved_searches")
    op.drop_table("saved_searches")
    op.drop_index("ix_saved_reports_user", table_name="saved_reports")
    op.drop_table("saved_reports")
    op.drop_index("ix_refresh_tokens_user", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index("ix_notification_rules_user", table_name="notification_rules")
    op.drop_table("notification_rules")
    op.drop_index("ix_audit_log_user_time", table_name="audit_log")
    op.drop_index("ix_audit_log_action_time", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index("ix_api_keys_user", table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_table("users")
    op.drop_table("ranking_configs")
    op.drop_table("languages")
    op.drop_index("ix_events_status_updated", table_name="events")
    op.drop_index("ix_events_confidence", table_name="events")
    op.drop_table("events")
    op.drop_table("countries")
    op.drop_table("categories")
    # ### end Alembic commands ###
